### ISSUE TITLE
Use api_name as added prefix 

### ISSUE THREAD

**Issue by royboy789** [SkyPressATX/war-api#14]
I like that the framework automatically adds new custom tables, I think however that it should be prefixed with the api_name.  
  
For example if your api_name is `war` all tables will be (assuming default prefix) `wp_war` vs. just the default as to avoid confusion. This also limits if you want to create another data set called `posts` or other naming convention that is already used.   
  
If the purpose of NOT using the api_name as a prefix is to tap into existing tables and store data there, maybe it would be smart to add it in is a capability of either the data model (so each data model can choose to be prefixed default or not)

**Comment by BMO-tech** [comment]
That's a good suggestion, also shouldn't be too hard to do.

**Comment by BMO-tech** [comment]
![screen shot 2017-06-19 at 12 31 11 pm](https://user-images.githubusercontent.com/7051219/27297644-627a00c2-54eb-11e7-8ae9-6583e87adc1d.png)
<img width="185" alt="screen shot 2017-06-19 at 12 31 45 pm" src="https://user-images.githubusercontent.com/7051219/27297649-66028390-54eb-11e7-81d7-39430d865874.png">

Like this?

```
    'table_prefix' => '',
```

Using this on the Data Model mapping will prevent any additional pre-fixing to happen. Where as, if you don't specify it, then the `api_name` set in `war_config` will be used (plus an underscore `_`)

This also means that if you set a custom `table_prefix`, then it will need to include it's own underscore:

```
'table_prefix' => 'hamburger_'
```

**Comment by royboy789** [comment]
👍
