### ISSUE TITLE
User Error when no user

### ISSUE THREAD

**Issue by royboy789** [SkyPressATX/war-api#19]
Undefined property: stdClass::$user_email in __/srv/www/ezdata/public_html/wp-content/plugins/war-api/src/War_User.class.php__ on line __47__  
 
I fixed this with adding in 
```
if( ! $this->current_user->ID ) { return false }
```
on line __45__

**Comment by BMO-tech** [comment]
PR Merged:

https://github.com/SkyPressATX/war-api/pull/23
